story: |
  # Hi! I'm André.

  I’ve been shaping tech environments for more than 15 years, bringing technology and business together. During that time, I’ve worked for startup’s, scaleup’s, up to big corporations. I have profound experience in software engineering and even more experience on the leadership side. In this role, I’m building and guiding organizations and transforming companies and their business on a tactical and strategic level. In recent years I was primarily working as a Chief Technology Officer.

  I've studied informatics and, later on, business economics. Yet to say, my focus is still on technology. I have a strong passion for technical topics, especially technology trends and their usage to drive innovation. Besides that, I've led various projects, from technical migrations to post-acquisition integrations. Finally, I'm an advocate of modern leadership and progressive organizational design. I have extensive experience in transforming organizations into sustainable technology powerhouses.

  I like to share my experience at conferences and support companies - as advisor and business angel - in mastering their technical challenges.

  Don't hesitate to reach out to me. I'm always open for a chat.

logo: /assets/img/AndreNeubauer_sm.jpg
remote_theme: devpg/minimal
color-scheme: dark

plugins:
  - jekyll-remote-theme
